import type { SequenceTemplate, Tier } from './types'

export const b2b21dFull: SequenceTemplate = {
  sequence_name: 'b2b-21d-full',
  program: 'b2b',
  tier: 'A',
  label: 'Tier A — Completo (Email + LinkedIn + Tel)',
  description: '11 touches en 21 días. Email + LinkedIn + WhatsApp + SMS + Voicemail + Llamada.',
  duration_days: 21,
  touches: 11,
  required_fields: ['email', 'linkedin_url', 'phone'],
  steps: [
    {
      sequence_name: 'b2b-21d-full',
      step_number: 1,
      offset_days: 0,
      channel: 'email',
      action_type: 'email_audit',
      provider: 'smartlead',
      template_id: 'smartlead-b2b-d1-audit',
      required_assets: ['video_sendspark'],
      required_fields: ['email'],
      delivery_mode: 'external_sequence',
      notes: 'Email #1 — "{{marca}} pierde visibilidad sin video" + link auditoría Sendspark.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 2,
      offset_days: 3,
      channel: 'linkedin',
      action_type: 'linkedin_invite',
      provider: 'waalaxy',
      template_id: 'waalaxy-campaign-connectMessage',
      required_assets: [],
      required_fields: ['linkedin_url'],
      delivery_mode: 'task_driven',
      notes: 'Solicitud de conexión + DM post-acceptance. Tipo connectMessage Waalaxy.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 3,
      offset_days: 4,
      channel: 'email',
      action_type: 'email_followup',
      provider: 'smartlead',
      template_id: 'smartlead-b2b-d5-followup-{signal}',
      required_assets: ['email_html_B', 'email_html_C', 'email_html_D'],
      required_fields: ['email'],
      delivery_mode: 'external_sequence',
      signal_depends_on: 1,
      notes: 'Email #2 adapta variante según señal del Día 1 (B/C/D).',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 4,
      offset_days: 6,
      channel: 'voice',
      action_type: 'voicemail_audit',
      provider: 'pendiente',
      template_id: null,
      required_assets: ['voice_default'],
      required_fields: ['phone'],
      delivery_mode: 'task_driven',
      notes: 'Buzón de voz 45s (Orum o similar). Herramienta pendiente.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 5,
      offset_days: 6,
      channel: 'sms',
      action_type: 'sms_audit_link',
      provider: 'pendiente',
      template_id: null,
      required_assets: [],
      required_fields: ['phone'],
      delivery_mode: 'task_driven',
      notes: 'SMS con link a auditoría. Mismo día que voicemail. Herramienta pendiente.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 6,
      offset_days: 7,
      channel: 'whatsapp',
      action_type: 'wa_followup',
      provider: 'respondio',
      template_id: 'respondio-wa-followup-{signal}',
      required_assets: [],
      required_fields: ['phone'],
      delivery_mode: 'task_driven',
      signal_depends_on: 3,
      notes: 'WhatsApp texto adaptado según señal del Email #2.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 7,
      offset_days: 9,
      channel: 'linkedin',
      action_type: 'linkedin_engagement',
      provider: 'manual',
      template_id: null,
      required_assets: [],
      required_fields: ['linkedin_url'],
      delivery_mode: 'manual',
      notes: 'Engagement orgánico (like/comentario). CERO mención comercial. Tarea manual.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 8,
      offset_days: 11,
      channel: 'email',
      action_type: 'email_fomo',
      provider: 'brevo',
      template_id: 'brevo-b2b-d12-fomo-{signal}',
      required_assets: [
        'email_html_B',
        'email_html_C',
        'email_html_D',
        'microsite',
      ],
      required_fields: ['email'],
      delivery_mode: 'task_driven',
      signal_depends_on: 6,
      notes: 'Email #3 FOMO competitivo. Variante según señal del WA followup.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 9,
      offset_days: 14,
      channel: 'whatsapp',
      action_type: 'wa_voice_note',
      provider: 'respondio',
      template_id: 'respondio-wa-voice-{signal}',
      required_assets: ['voice_B', 'voice_C', 'voice_D'],
      required_fields: ['phone'],
      delivery_mode: 'task_driven',
      signal_depends_on: 8,
      notes: 'Nota de voz < 60s. Variante según señal del Email #3.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 10,
      offset_days: 17,
      channel: 'voice',
      action_type: 'call_conversion',
      provider: 'manual',
      template_id: null,
      required_assets: [],
      required_fields: ['phone'],
      delivery_mode: 'manual',
      signal_depends_on: 'accumulated',
      notes: 'Llamada manual. Script hot/mixed/cold según acumulado de señales B.',
    },
    {
      sequence_name: 'b2b-21d-full',
      step_number: 11,
      offset_days: 20,
      channel: 'email',
      action_type: 'email_breakup',
      provider: 'brevo',
      template_id: 'brevo-b2b-d21-breakup',
      required_assets: ['email_html_breakup'],
      required_fields: ['email'],
      delivery_mode: 'task_driven',
      notes: 'Email breakup — "Cierro tu archivo, {{nombre}}?" Fijo.',
    },
  ],
}

export const b2b21dStandard: SequenceTemplate = {
  sequence_name: 'b2b-21d-standard',
  program: 'b2b',
  tier: 'B',
  label: 'Tier B — Parcial (Email + LinkedIn)',
  description: '9 touches en 21 días. Sin WhatsApp voz, sin SMS, sin voicemail.',
  duration_days: 21,
  touches: 9,
  required_fields: ['email', 'linkedin_url'],
  steps: [
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 1,
      offset_days: 0,
      channel: 'email',
      action_type: 'email_audit',
      provider: 'smartlead',
      template_id: 'smartlead-b2b-d1-audit',
      required_assets: ['video_sendspark'],
      required_fields: ['email'],
      delivery_mode: 'external_sequence',
      notes: 'Email #1 auditoría + video Sendspark.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 2,
      offset_days: 3,
      channel: 'linkedin',
      action_type: 'linkedin_invite',
      provider: 'waalaxy',
      template_id: 'waalaxy-campaign-connectMessage',
      required_assets: [],
      required_fields: ['linkedin_url'],
      delivery_mode: 'task_driven',
      notes: 'Solicitud conexión + DM.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 3,
      offset_days: 4,
      channel: 'email',
      action_type: 'email_followup',
      provider: 'smartlead',
      template_id: 'smartlead-b2b-d5-followup-{signal}',
      required_assets: ['email_html_B', 'email_html_C', 'email_html_D'],
      required_fields: ['email'],
      delivery_mode: 'external_sequence',
      signal_depends_on: 1,
      notes: 'Email #2 adaptado por señal Día 1.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 4,
      offset_days: 6,
      channel: 'whatsapp',
      action_type: 'wa_followup',
      provider: 'respondio',
      template_id: 'respondio-wa-followup-{signal}',
      required_assets: [],
      required_fields: ['phone'],
      delivery_mode: 'task_driven',
      signal_depends_on: 3,
      notes: 'WA texto. Si no hay phone → skipped.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 5,
      offset_days: 9,
      channel: 'linkedin',
      action_type: 'linkedin_engagement',
      provider: 'manual',
      template_id: null,
      required_assets: [],
      required_fields: ['linkedin_url'],
      delivery_mode: 'manual',
      notes: 'Engagement orgánico LinkedIn. Manual.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 6,
      offset_days: 11,
      channel: 'email',
      action_type: 'email_fomo',
      provider: 'brevo',
      template_id: 'brevo-b2b-d12-fomo-{signal}',
      required_assets: [
        'email_html_B',
        'email_html_C',
        'email_html_D',
        'microsite',
      ],
      required_fields: ['email'],
      delivery_mode: 'task_driven',
      signal_depends_on: 4,
      notes: 'Email #3 FOMO competitivo.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 7,
      offset_days: 14,
      channel: 'whatsapp',
      action_type: 'wa_voice_note',
      provider: 'respondio',
      template_id: 'respondio-wa-voice-{signal}',
      required_assets: ['voice_B', 'voice_C', 'voice_D'],
      required_fields: ['phone'],
      delivery_mode: 'task_driven',
      signal_depends_on: 6,
      notes: 'Nota de voz WhatsApp (solo LatAm). Opcional si no hay phone.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 8,
      offset_days: 17,
      channel: 'voice',
      action_type: 'call_conversion',
      provider: 'manual',
      template_id: null,
      required_assets: [],
      required_fields: ['phone'],
      delivery_mode: 'manual',
      signal_depends_on: 'accumulated',
      notes: 'Llamada manual. Opcional si no hay phone.',
    },
    {
      sequence_name: 'b2b-21d-standard',
      step_number: 9,
      offset_days: 20,
      channel: 'email',
      action_type: 'email_breakup',
      provider: 'brevo',
      template_id: 'brevo-b2b-d21-breakup',
      required_assets: ['email_html_breakup'],
      required_fields: ['email'],
      delivery_mode: 'task_driven',
      notes: 'Email breakup fijo.',
    },
  ],
}

export const b2b18dEmail: SequenceTemplate = {
  sequence_name: 'b2b-18d-email',
  program: 'b2b',
  tier: 'C',
  label: 'Tier C — Mínimo (Solo email)',
  description: '5 touches en 18 días. Solo canal email.',
  duration_days: 18,
  touches: 5,
  required_fields: ['email'],
  steps: [
    {
      sequence_name: 'b2b-18d-email',
      step_number: 1,
      offset_days: 0,
      channel: 'email',
      action_type: 'email_audit',
      provider: 'smartlead',
      template_id: 'smartlead-b2b-d1-audit',
      required_assets: ['video_sendspark'],
      required_fields: ['email'],
      delivery_mode: 'external_sequence',
      notes: 'Email #1 auditoría + video.',
    },
    {
      sequence_name: 'b2b-18d-email',
      step_number: 2,
      offset_days: 4,
      channel: 'email',
      action_type: 'email_followup',
      provider: 'smartlead',
      template_id: 'smartlead-b2b-d5-followup-{signal}',
      required_assets: ['email_html_B', 'email_html_C', 'email_html_D'],
      required_fields: ['email'],
      delivery_mode: 'external_sequence',
      signal_depends_on: 1,
      notes: 'Email #2 adaptado por señal.',
    },
    {
      sequence_name: 'b2b-18d-email',
      step_number: 3,
      offset_days: 9,
      channel: 'email',
      action_type: 'email_fomo',
      provider: 'brevo',
      template_id: 'brevo-b2b-d10-fomo-{signal}',
      required_assets: [
        'email_html_B',
        'email_html_C',
        'email_html_D',
        'microsite',
      ],
      required_fields: ['email'],
      delivery_mode: 'task_driven',
      signal_depends_on: 2,
      notes: 'Email #3 FOMO competitivo.',
    },
    {
      sequence_name: 'b2b-18d-email',
      step_number: 4,
      offset_days: 13,
      channel: 'email',
      action_type: 'email_casestudy',
      provider: 'brevo',
      template_id: 'brevo-b2b-d14-casestudy-{signal}',
      required_assets: ['email_html_B', 'email_html_C', 'email_html_D'],
      required_fields: ['email'],
      delivery_mode: 'task_driven',
      signal_depends_on: 3,
      notes: 'Email #4 caso de estudio.',
    },
    {
      sequence_name: 'b2b-18d-email',
      step_number: 5,
      offset_days: 17,
      channel: 'email',
      action_type: 'email_breakup',
      provider: 'brevo',
      template_id: 'brevo-b2b-d18-breakup',
      required_assets: ['email_html_breakup'],
      required_fields: ['email'],
      delivery_mode: 'task_driven',
      notes: 'Email breakup fijo.',
    },
  ],
}

export const B2B_TEMPLATES: SequenceTemplate[] = [
  b2b21dFull,
  b2b21dStandard,
  b2b18dEmail,
]

export const ALL_TEMPLATES: SequenceTemplate[] = [...B2B_TEMPLATES]

export function resolveTierByData(data: {
  email?: string
  linkedin_url?: string
  phone?: string
}): Tier {
  if (!data.email) return 'none'
  if (data.email && data.linkedin_url && data.phone) return 'A'
  if (data.email && data.linkedin_url) return 'B'
  return 'C'
}

export function getTemplateByTier(tier: Tier): SequenceTemplate | null {
  return B2B_TEMPLATES.find((t) => t.tier === tier) ?? null
}
