export interface ProcurementRow {
  tool: string
  url?: string
  currentPlan: string
  discovered: string
  options: { label: string; cost: string; note: string }[]
  recommended: string
  recommendedCost: string
  category: 'subscription' | 'free' | 'optional' | 'removed'
}

export const PROCUREMENT_ANALYSIS: ProcurementRow[] = [
  // --- Suscripciones con nivel por definir ---
  {
    tool: 'Clay',
    url: 'https://www.clay.com/pricing',
    currentPlan: 'Starter $149/mes',
    discovered: 'Starter no tiene Smartlead nativo ni HTTP API. Si se quiere automatización completa se necesita Growth.',
    options: [
      { label: 'A) Starter $149', cost: '$149/mes', note: 'Todo manual: CSV exports para Smartlead, Expandi, Supabase' },
      { label: 'B) Launch $185', cost: '$185/mes', note: 'Smartlead NATIVO. Expandi y Supabase manual (CSV + scripts Gabriel)' },
      { label: 'C) Growth $495', cost: '$495/mes', note: 'TODO automático: Smartlead + HTTP API (Expandi) + Webhooks (Supabase). 6,000 créditos' },
    ],
    recommended: 'C) Growth $495 si se autoriza automatización. B) Launch $185 si se autoriza manual',
    recommendedCost: '$185 - $495/mes',
    category: 'subscription',
  },
  {
    tool: 'HubSpot CRM (3 cuentas)',
    url: 'https://www.hubspot.com/pricing',
    currentPlan: 'Free $0',
    discovered: 'Free no tiene workflows automáticos. Se necesitan 3 cuentas: 1 Equipo 3 + 1 Pepe (Eq1) + 1 Mery (Eq2). Upgrade a Pro en Semana 3 para workflows.',
    options: [
      { label: 'A) Free $0', cost: '$0', note: 'Pipelines + contactos. Sin workflows, sin scoring, sin secuencias' },
      { label: 'B) Starter ×3 → Pro ×3', cost: '$60→$270/mes', note: 'Sem 1-2: Starter $20×3=$60. Sem 3-4: Pro $90×3=$270. Workflows, scoring, sequences' },
    ],
    recommended: 'B) Starter→Pro (3 cuentas). Total Mes 1: ~$330',
    recommendedCost: '$60→$270/mes',
    category: 'subscription',
  },
  {
    tool: 'Unbounce',
    url: 'https://unbounce.com/pricing',
    currentPlan: '$99/mes (solo B2B)',
    discovered: 'Plan Build $99 cubre AMBOS micrositios (B2B + Creadores). Reemplaza Leadpages. DTR, hidden fields, webhooks, HubSpot nativo.',
    options: [
      { label: 'A) Build $99', cost: '$99/mes', note: 'DTR, webhooks, HubSpot nativo, páginas ilimitadas. Cubre B2B + Creadores' },
      { label: 'B) Experiment $149', cost: '$149/mes', note: 'Todo de Build + A/B testing + Smart Traffic' },
    ],
    recommended: 'A) Build $99',
    recommendedCost: '$99/mes',
    category: 'subscription',
  },
  {
    tool: 'Expandi',
    url: 'https://expandi.io/pricing',
    currentPlan: '$99/mes',
    discovered: 'Tiene integración nativa con HubSpot (bidireccional). Verificar que plan $99 la incluye (B19).',
    options: [
      { label: 'Plan base $99', cost: '$99/mes', note: 'Verificar HubSpot integration incluida. Si no → evaluar upgrade o Zapier puente' },
    ],
    recommended: 'Plan base $99 (verificar B19)',
    recommendedCost: '$99/mes',
    category: 'subscription',
  },
  {
    tool: 'ManyChat Pro',
    url: 'https://manychat.com/pricing',
    currentPlan: '$65/mes (5K contactos)',
    discovered: 'Correcto para sprint. Si Mes 2 escala a 25K contactos → $235/mes.',
    options: [
      { label: 'A) Pro 5K $65', cost: '$65/mes', note: 'Suficiente para sprint (1,000 prospectos + creadores)' },
      { label: 'B) Pro 25K $235', cost: '$235/mes', note: 'Si Mes 2 escala volumen' },
    ],
    recommended: 'A) Pro 5K $65',
    recommendedCost: '$65/mes',
    category: 'subscription',
  },
  // --- Herramientas sin cambio de plan ---
  {
    tool: 'Smartlead',
    url: 'https://smartlead.ai/pricing',
    currentPlan: '$94/mes',
    discovered: 'Ya contratado. 15 cuentas warmup + rotación. Correcto.',
    options: [{ label: 'Plan actual $94', cost: '$94/mes', note: 'Ya contratado. Sin cambios.' }],
    recommended: 'Plan actual $94',
    recommendedCost: '$94/mes',
    category: 'subscription',
  },
  {
    tool: 'Google Workspace (15 cuentas)',
    url: 'https://workspace.google.com/pricing',
    currentPlan: '~$108/mes',
    discovered: '15 cuentas nuevas en 5 dominios (4 existentes + 1 por comprar).',
    options: [{ label: '$7.20 × 15 cuentas', cost: '$108/mes', note: 'Business Starter. SMTP/IMAP para Smartlead.' }],
    recommended: '$108/mes',
    recommendedCost: '$108/mes',
    category: 'subscription',
  },
  {
    tool: 'SmartScout',
    url: 'https://www.smartscout.com/pricing',
    currentPlan: '$97/mes',
    discovered: 'Ya contratado. API no incluida (plan superior). UI manual suficiente para sprint.',
    options: [{ label: 'Plan actual $97', cost: '$97/mes', note: 'API no incluida. Para Fase 2 (Mes 2) evaluar plan con API.' }],
    recommended: 'Plan actual $97',
    recommendedCost: '$97/mes',
    category: 'subscription',
  },
  {
    tool: 'Apify',
    url: 'https://apify.com/pricing',
    currentPlan: '$49/mes',
    discovered: 'Ya contratado. API incluida. Correcto.',
    options: [{ label: 'Plan actual $49', cost: '$49/mes', note: 'Ya contratado. API incluida.' }],
    recommended: 'Plan actual $49',
    recommendedCost: '$49/mes',
    category: 'subscription',
  },
  {
    tool: 'Sendspark',
    url: 'https://www.sendspark.com/pricing',
    currentPlan: '$129/mes',
    discovered: 'Video personalizado B2B. Correcto.',
    options: [{ label: 'Pro $129', cost: '$129/mes', note: 'Variables dinámicas por prospecto.' }],
    recommended: 'Pro $129',
    recommendedCost: '$129/mes',
    category: 'subscription',
  },
  {
    tool: 'ElevenLabs',
    url: 'https://elevenlabs.io/pricing',
    currentPlan: '$99/mes',
    discovered: 'Clonación de voz IA. Correcto.',
    options: [{ label: 'Creator $99', cost: '$99/mes', note: 'Entrenamiento clon + API ManyChat.' }],
    recommended: 'Creator $99',
    recommendedCost: '$99/mes',
    category: 'subscription',
  },
  {
    tool: 'Klaviyo',
    url: 'https://www.klaviyo.com/pricing',
    currentPlan: '$20/mes',
    discovered: 'SMS recuperación abandono Elevn. Correcto.',
    options: [{ label: 'Plan base $20', cost: '$20/mes', note: 'Correcto para sprint.' }],
    recommended: 'Plan base $20',
    recommendedCost: '$20/mes',
    category: 'subscription',
  },
  {
    tool: 'JustCall',
    url: 'https://justcall.io/pricing',
    currentPlan: '$30/mes',
    discovered: '1 usuario. Correcto.',
    options: [{ label: 'Plan base $30', cost: '$30/mes', note: '1 usuario, llamadas Día 18.' }],
    recommended: 'Plan base $30',
    recommendedCost: '$30/mes',
    category: 'subscription',
  },
  {
    tool: 'Twilio',
    url: 'https://www.twilio.com/pricing',
    currentPlan: '~$30/mes',
    discovered: 'Pay per use. Registro A2P puede tardar semanas.',
    options: [{ label: 'Pay per use', cost: '~$30/mes', note: 'Iniciar registro A2P temprano.' }],
    recommended: '~$30/mes',
    recommendedCost: '~$30/mes',
    category: 'subscription',
  },
  {
    tool: 'Relay.app',
    url: 'https://www.relay.app/pricing',
    currentPlan: '$9/mes',
    discovered: 'Tiene: Smartlead, ManyChat, Twilio, Calendly, HubSpot, Telegram. No tiene: Expandi, Sendspark, Unbounce.',
    options: [{ label: 'Plan base $9', cost: '$9/mes', note: 'Correcto. Expandi via HubSpot.' }],
    recommended: 'Plan base $9',
    recommendedCost: '$9/mes',
    category: 'subscription',
  },
  {
    tool: 'Outgrow',
    url: 'https://outgrow.co/pricing',
    currentPlan: '$22/mes',
    discovered: 'Calculadoras interactivas. Correcto.',
    options: [{ label: 'Freelancer $22', cost: '$22/mes', note: 'Correcto.' }],
    recommended: 'Freelancer $22',
    recommendedCost: '$22/mes',
    category: 'subscription',
  },
  {
    tool: 'Social Blade',
    url: 'https://socialblade.com',
    currentPlan: '$4/mes',
    discovered: 'Analytics creadores. Correcto.',
    options: [{ label: 'Plan base $4', cost: '$4/mes', note: 'Correcto.' }],
    recommended: 'Plan base $4',
    recommendedCost: '$4/mes',
    category: 'subscription',
  },
  {
    tool: 'Visualping',
    url: 'https://visualping.io/pricing',
    currentPlan: '$25/mes',
    discovered: 'Monitoreo competitivo. Semana 3+.',
    options: [{ label: 'Plan base $25', cost: '$25/mes', note: 'Semana 3+.' }],
    recommended: 'Plan base $25',
    recommendedCost: '$25/mes',
    category: 'subscription',
  },
  // --- Costos únicos ---
  {
    tool: '1 Dominio (GoDaddy)',
    url: 'https://www.godaddy.com',
    currentPlan: '5 dominios ~$60',
    discovered: '4 ya comprados. Solo 1 por comprar (nombre por definir B01).',
    options: [{ label: '1 dominio', cost: '~$12 único', note: '4 ya existen: elevnhub, elevnpro, lanetahub, lanetapro.' }],
    recommended: '~$12 único',
    recommendedCost: '~$12 único',
    category: 'subscription',
  },
  {
    tool: 'Slybroadcast',
    url: 'https://www.slybroadcast.com',
    currentPlan: '$175 paquete',
    discovered: 'Voicemail sin timbre. No tiene HubSpot (G1).',
    options: [{ label: 'Paquete $175', cost: '$175 único', note: 'No logea en HubSpot. Ver G1.' }],
    recommended: '$175 único',
    recommendedCost: '$175 único',
    category: 'subscription',
  },
  // --- Eliminadas ---
  {
    tool: 'Leadpages',
    url: 'https://www.leadpages.com/pricing',
    currentPlan: '$49/mes',
    discovered: 'DESCARTADA. Unbounce Build cubre B2B + Creadores.',
    options: [{ label: 'Eliminar', cost: '$0', note: 'Ahorro $49/mes. Unbounce Build lo reemplaza.' }],
    recommended: 'Eliminar',
    recommendedCost: '$0 (ahorro $49)',
    category: 'removed',
  },
  // --- Gratuitas ---
  {
    tool: 'Telegram',
    url: 'https://telegram.org',
    currentPlan: 'Free',
    discovered: 'Reemplazó Slack.',
    options: [{ label: 'Free', cost: '$0', note: '' }],
    recommended: 'Free',
    recommendedCost: '$0',
    category: 'free',
  },
  {
    tool: 'Branch.io',
    url: 'https://www.branch.io/pricing',
    currentPlan: 'Free',
    discovered: 'Deep linking <10K clicks.',
    options: [{ label: 'Free', cost: '$0', note: '' }],
    recommended: 'Free',
    recommendedCost: '$0',
    category: 'free',
  },
  {
    tool: 'Calendly',
    url: 'https://calendly.com/pricing',
    currentPlan: 'No estaba',
    discovered: 'CTA micrositios. HubSpot nativo.',
    options: [{ label: 'Free', cost: '$0', note: '' }],
    recommended: 'Free',
    recommendedCost: '$0',
    category: 'free',
  },
  {
    tool: 'Zapier',
    url: 'https://zapier.com/pricing',
    currentPlan: 'No estaba',
    discovered: 'Backup integraciones (ManyChat→HubSpot).',
    options: [{ label: 'Free (100 tasks)', cost: '$0', note: '' }],
    recommended: 'Free',
    recommendedCost: '$0',
    category: 'free',
  },
  // --- Opcionales ---
  {
    tool: 'LinkedIn Sales Navigator',
    url: 'https://business.linkedin.com/sales-solutions/compare-plans',
    currentPlan: 'Opcional',
    discovered: 'Para enrichment Clay mejorado.',
    options: [{ label: '$100/usuario', cost: '$100/mes', note: 'Evaluar Día 3.' }],
    recommended: 'Evaluar',
    recommendedCost: '$100/mes',
    category: 'optional',
  },
  {
    tool: 'Agente voz IA (Synthflow)',
    url: 'https://www.synthflow.ai/pricing',
    currentPlan: 'Opcional',
    discovered: 'Llamadas autónomas B2B.',
    options: [{ label: '$29-500', cost: '$29-500/mes', note: 'Evaluar Día 4.' }],
    recommended: 'Evaluar',
    recommendedCost: '$29-500/mes',
    category: 'optional',
  },
  {
    tool: 'Routable',
    url: 'https://routable.com',
    currentPlan: 'Opcional',
    discovered: 'Pagos masivos creadores. Puede ser Mes 2.',
    options: [{ label: '~$500', cost: '~$500/mes', note: 'Evaluar Semana 3.' }],
    recommended: 'Mes 2',
    recommendedCost: '~$500/mes',
    category: 'optional',
  },
]

export const COST_SCENARIOS = {
  growth: {
    name: 'Escenario A: Clay Growth $495 (automatización completa)',
    clay: 495,
    hubspot_sem12: 60,
    hubspot_sem34: 270,
    otherMonthly: 94 + 108 + 97 + 49 + 99 + 99 + 65 + 30 + 30 + 9 + 20 + 22 + 4 + 25 + 129 + 99,
    unique: 12 + 175,
    get totalSem12() { return this.clay + this.hubspot_sem12 + this.otherMonthly },
    get totalSem34() { return this.clay + this.hubspot_sem34 + this.otherMonthly },
  },
  launch: {
    name: 'Escenario B: Clay Launch $185 (Smartlead auto, resto manual)',
    clay: 185,
    hubspot_sem12: 60,
    hubspot_sem34: 270,
    otherMonthly: 94 + 108 + 97 + 49 + 99 + 99 + 65 + 30 + 30 + 9 + 20 + 22 + 4 + 25 + 129 + 99,
    unique: 12 + 175,
    get totalSem12() { return this.clay + this.hubspot_sem12 + this.otherMonthly },
    get totalSem34() { return this.clay + this.hubspot_sem34 + this.otherMonthly },
  },
}
